# Google Documents

This example is a stub (currently is a sheets copy)

In [1]:
import pandas as pd

from dsgcp import credentials
from dsgcp import sheets

In [2]:
pd.set_option('display.max_rows', 3000)
pd.set_option("max_colwidth", 200)
pd.set_option('display.max_columns', 100)

### Load shared variables

In [3]:
%store -r cred_file
%store -r project_id

In [4]:
c, p = credentials.create_credentials(cred_file,
                                      project_id=project_id)

#### GCP Project Id to run queries from

More scopes could be added with: 
```
credentials = gcp_client.with_scopes(
    [
        'https://www.googleapis.com/auth/cloud-platform',
        'https://www.googleapis.com/auth/drive',
        'https://www.googleapis.com/auth/spreadsheets'
    ]
)
```

In [5]:
df_upload = pd.DataFrame({'a':[1,2,3], 
                          'b':[4,5,6], 
                          'c':[12,11,10]})

In [6]:
df_upload

   a  b   c
0  1  4  12
1  2  5  11
2  3  6  10

## Google Sheets Access  
1. Enable the Google Sheets API
2. Get unique sheet ID from target Sheet URL
3. Share Sheet with service account the current credentials are granted from

In [7]:
sheet_id = '1a2AXLFtIbfvgHtzX22XMDwg-5QRkrT7IaUMEc1DCHwE'

In [8]:
worksheet_id = 'loopback'

In [9]:
sheets.write?

Signature:
sheets.write(
    credentials,
    worksheet_id,
    sheet_id,
    df,
    replace=True,
    **kwargs,
)
Docstring:
Read a worksheet from a Google Sheet.

Notes
-----
sheet_id can be copied from the URL or retrieved with:
    gspread_pandas.client.Client.list_spreadsheet_files_in_folder

Parameters
----------
credentials : google.oauth2.service_account.Credentials instance
worksheet_id : str, unique name of worksheet to download
sheet_id : str, unique ID of Sheet
df : Pandas DataFrame to upload
replace : bool, replace existing data in worksheet
**kwargs : keyword arguments to pass to gspread_pandas.spread.Spread.df_to_sheet

Returns
-------
None
File:      ~/code/dsgcp/dsgcp/sheets.py
Type:      function

In [10]:
sheets.write(credentials=c, 
             worksheet_id=worksheet_id, 
             sheet_id=sheet_id,
             df=df_upload,
             replace=True, 
             index=False)

In [11]:
sheets.read?

Signature: sheets.read(credentials, worksheet_id, sheet_id, **kwargs)
Docstring:
Load a Google Sheet into a Pandas DataFrame.

Notes
-----
Google Sheets API must be enabled in the project the credentials are based in.

Parameters
----------
credentials : google.oauth2.service_account.Credentials instance
worksheet_id : str, unique name of worksheet to download
sheet_id : str, unique ID of Sheet
**kwargs : keyword arguments to pass to gspread_pandas.spread.Spread.sheet_to_df

Returns
-------
Pandas DataFrame
File:      ~/code/dsgcp/dsgcp/sheets.py
Type:      function

Note that from the Sheet, the first row is actually the column header, so we use `header_rows=1`

In [12]:
df_download = sheets.read(credentials=c,
                          worksheet_id=worksheet_id,
                          sheet_id=sheet_id,
                          header_rows=1)

In [13]:
df_download

   a  b   c
0  1  4  12
1  2  5  11
2  3  6  10