# Secret Manager  

#### ToDos:  
1. Add docstrings to secret.py

In [1]:
import pandas as pd

from dsgcp import credentials
from dsgcp import secret

### Load shared variables

In [2]:
%store -r cred_file
%store -r project_id

In [3]:
c, p = credentials.create_credentials(cred_file,
                                      project_id=project_id)

### List all secret in the Project

In [4]:
secret.list_all(credentials=c, project_id=project_id)

               project   name                          creation labels
0  sada-colin-dietrich  test1  2022-07-09T16:09:43.816386+00:00     {}

### Get Secret Value

In [13]:
secret.access?

Signature: secret.access(credentials, project_id, secret_id, version_id='latest')
Docstring:
Use Secret Manager to retrieve information

Parameters
----------
credentials :
project_id :
secret_id :
version_id :

Returns
-------
str, UTF-8 decoded payload stored in Secret Manager
File:      ~/code/dsgcp/dsgcp/secret.py
Type:      function

In [5]:
secret.access(credentials=c, project_id=project_id, secret_id='test1')

'Hello Secrets 1!'

### Set, Access and Delete a Secret

In [6]:
test_secret_id = 'test_A'

In [14]:
secret.create?

Signature: secret.create(credentials, project_id, secret_id, labels=None)
Docstring:
Add a Secret

Parameters
----------
credentials : google.cloud.XX credentials
project_id : str, GCP project name
secret_id : str, secret name
labels : dict, key value labels to apply to the secret
File:      ~/code/dsgcp/dsgcp/secret.py
Type:      function

In [7]:
secret.create(credentials=c, 
               project_id=project_id, 
               secret_id=test_secret_id,
               labels={'test_label': 'fun_description'})

name: "projects/580722667530/secrets/test_A"
replication {
  automatic {
  }
}
create_time {
  seconds: 1663968563
  nanos: 925762000
}
labels {
  key: "test_label"
  value: "fun_description"
}
etag: "\"15e95edf2b9302\""

In [15]:
secret.add_version?

Signature: secret.add_version(credentials, project_id, secret_id, payload)
Docstring:
Parameters
----------
credentials : google.cloud.XX credentials
project_id : str, GCP project name
secret_id : str, secret name
payload : str, value set secret

Returns
-------
str, secret version
File:      ~/code/dsgcp/dsgcp/secret.py
Type:      function

In [8]:
secret.add_version(credentials=c,
                    project_id=project_id,
                    secret_id=test_secret_id,
                    payload=f'Test Secret Hello World!'
                   )

'projects/580722667530/secrets/test_A/versions/1'

In [9]:
secret.list_all(credentials=c, project_id=project_id)

,project,name,creation,labels
0,sada-colin-dietrich,test1,2022-07-09T16:09:43.816386+00:00,{}
1,sada-colin-dietrich,test_A,2022-09-23T21:29:23.925762+00:00,{'test_label': 'fun_description'}

In [10]:
secret.access(credentials=c,
               project_id=project_id,
               secret_id=test_secret_id
               )

'Test Secret Hello World!'

In [11]:
secret.delete(credentials=c,
               project_id=project_id,
               secret_id=test_secret_id
               )

In [12]:
secret.list_all(credentials=c, project_id=project_id)

               project   name                          creation labels
0  sada-colin-dietrich  test1  2022-07-09T16:09:43.816386+00:00     {}